name: React-toastify CI

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Install node
        uses: actions/setup-node@v4.1.0
        with:
            node-version: '22.x'
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
            version: 9 
      - name: Install dependencies
        run: pnpm i 
      # - name: Lint
      #   run: yarn lint
      - name: Setup
        run: pnpm run setup
      - name: Build
        run: pnpm build
      - name: Test
        run: pnpm run test:run 
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos
      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v2.3.4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
